{
 "title": "Phonebook App",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_processing_seconds_sum/http_request_processing_seconds_count"
    }
   ]
  },
  {
   "title": "Requests per method",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (endpoint)(irate(http_requests_total[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}
{
 "title": "Node Exporter Full",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "name",
    "label": "Host:",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info{nodename=\"$name\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_uname_info{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node:$port\",job=~\"$job\"}) / count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "avg(node_load15{instance=~\"$node:$port\",job=~\"$job\"}) / count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node:$port\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}) / (node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Sys Load (1m avg)",
   "type": "singlestat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node:$port\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"} - (node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU / Memory / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Percentage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "System - Processes executing in kernel mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "User - Normal processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Nice - Niced processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Idle - Waiting for something to happen"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Iowait - Waiting for I/O to complete"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Irq - Servicing interrupts"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Softirq - Servicing softirqs"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
      }
     ]
    },
    {
     "title": "Memory Stack",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_Slab_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_PageTables_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapCached_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Apps - Memory used by user-space applications"
      },
      {
       "expr": "node_memory_PageTables_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
      },
      {
       "expr": "node_memory_Slab_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Cache - Parked file data (file content) cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Unused - Free memory unassigned"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
       "legendFormat": "Swap - Swap space used"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "bps", "label": "Bits out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])*8",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])*8",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Disk Space Used",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk IOps",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$node:$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$node:$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "I/O Usage Read / Write",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$node:$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Successfully read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$node:$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Successfully written bytes"
      }
     ]
    },
    {
     "title": "I/O Usage Times",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node:$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"} [5m])",
       "legendFormat": "{{device}} - Time spent doing I/Os"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Meminfo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Active / Inactive",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Inactive - Memory which has been less recently used. It is more eligible to be reclaimed for other purposes"
      },
      {
       "expr": "node_memory_Active_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
      }
     ]
    },
    {
     "title": "Memory Commited",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
      },
      {
       "expr": "node_memory_CommitLimit_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "CommitLimit - Amount of memory currently available to be allocated on the system"
      }
     ]
    },
    {
     "title": "Memory Active / Inactive Detail",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_file_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Inactive_file - File-backed memory on inactive LRU list"
      },
      {
       "expr": "node_memory_Inactive_anon_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Inactive_anon - Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)"
      },
      {
       "expr": "node_memory_Active_file_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Active_file - File-backed memory on active LRU list"
      },
      {
       "expr": "node_memory_Active_anon_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Active_anon - Anonymous and swap cache on active least-recently-used (LRU) list, including tmpfs"
      }
     ]
    },
    {
     "title": "Memory Writeback and Dirty",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Writeback - Memory which is actively being written back to disk"
      },
      {
       "expr": "node_memory_WritebackTmp_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
      },
      {
       "expr": "node_memory_Dirty_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
      }
     ]
    },
    {
     "title": "Memory Shared and Mapped",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Mapped_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Mapped - Used memory in mapped pages files which have been mmaped, such as libraries"
      },
      {
       "expr": "node_memory_Shmem_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Shmem - Used shared memory (shared between several processes, thus including RAM disks)"
      }
     ]
    },
    {
     "title": "Memory Slab",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_SUnreclaim_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "SUnreclaim - Part of Slab, that cannot be reclaimed on memory pressure"
      },
      {
       "expr": "node_memory_SReclaimable_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "SReclaimable - Part of Slab, that might be reclaimed, such as caches"
      }
     ]
    },
    {
     "title": "Memory Vmalloc",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_VmallocChunk_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "VmallocChunk - Largest contigious block of vmalloc area which is free"
      },
      {
       "expr": "node_memory_VmallocTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "VmallocTotal - Total size of vmalloc memory area"
      },
      {
       "expr": "node_memory_VmallocUsed_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "VmallocUsed - Amount of vmalloc area which is used"
      }
     ]
    },
    {
     "title": "Memory Bounce",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Bounce_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Bounce - Memory used for block device bounce buffers"
      }
     ]
    },
    {
     "title": "Memory Anonymous",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_AnonHugePages_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "AnonHugePages - Memory in anonymous huge pages"
      },
      {
       "expr": "node_memory_AnonPages_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "AnonPages - Memory in user pages not backed by files"
      }
     ]
    },
    {
     "title": "Memory Kernel",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_KernelStack_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "KernelStack - Kernel memory stack. This is not reclaimable"
      }
     ]
    },
    {
     "title": "Memory HugePages Counter",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "node_memory_HugePages_Free{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "HugePages_Free - Huge pages in the pool that are not yet allocated"
      },
      {
       "expr": "node_memory_HugePages_Rsvd{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "HugePages_Rsvd - Huge pages for which a commitment to allocate from the pool has been made, but no allocation has yet been made"
      },
      {
       "expr": "node_memory_HugePages_Surp{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "HugePages_Surp - Huge pages in the pool above the value in /proc/sys/vm/nr_hugepages"
      }
     ]
    },
    {
     "title": "Memory HugePages Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_HugePages_Total{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "HugePages - Total size of the pool of huge pages"
      },
      {
       "expr": "node_memory_Hugepagesize_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Hugepagesize - Huge Page size"
      }
     ]
    },
    {
     "title": "Memory DirectMap",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_DirectMap1G_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "DirectMap1G - Amount of pages mapped as this size"
      },
      {
       "expr": "node_memory_DirectMap2M_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "DirectMap2M - Amount of pages mapped as this size"
      },
      {
       "expr": "node_memory_DirectMap4k_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "DirectMap4K - Amount of pages mapped as this size"
      }
     ]
    },
    {
     "title": "Memory Unevictable and MLocked",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Unevictable_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Unevictable - Amount of unevictable memory that can't be swapped out for a variety of reasons"
      },
      {
       "expr": "node_memory_Mlocked_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "MLocked - Size of pages locked to memory using the mlock() system call"
      }
     ]
    },
    {
     "title": "Memory NFS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_NFS_Unstable_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "NFS Unstable - Memory in NFS pages sent to the server, but not yet commited to the storage"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Vmstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pages In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Pages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgpgin{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "Pagesin - Page in operations"
      },
      {
       "expr": "irate(node_vmstat_pgpgout{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "Pagesout - Page out operations"
      }
     ]
    },
    {
     "title": "Memory Pages Swap In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Pages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pswpin{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "Pswpin - Pages swapped in"
      },
      {
       "expr": "irate(node_vmstat_pswpout{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "Pswpout - Pages swapped out"
      }
     ]
    },
    {
     "title": "Memory Page Faults",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Faults" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgfault{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgfault - Page major and minor fault operations"
      },
      {
       "expr": "irate(node_vmstat_pgmajfault{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgmajfault - Major page fault operations"
      },
      {
       "expr": "irate(node_vmstat_pgfault{instance=~\"$node:$port\",job=~\"$job\"}[5m]) - irate(node_vmstat_pgmajfault{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgminfault - Minor page fault operations"
      }
     ]
    }
   ]
  },
  {
   "title": "System Timesync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Syncronized Drift",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "node_timex_estimated_error_seconds{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Estimated error in seconds"
      },
      {
       "expr": "node_timex_offset_seconds{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Time offset in between local system and reference clock"
      },
      {
       "expr": "node_timex_maxerror_seconds{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Maximum error in seconds"
      }
     ]
    },
    {
     "title": "Time PLL Adjust",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "node_timex_loop_time_constant{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Phase-locked loop time adjust"
      }
     ]
    },
    {
     "title": "Time Syncronized Status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "node_timex_sync_status{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Is clock synchronized to a reliable server (1 = yes, 0 = no)"
      },
      {
       "expr": "node_timex_frequency_adjustment_ratio{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Local clock frequency adjustment"
      }
     ]
    },
    {
     "title": "Time Misc",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "s", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "node_timex_tick_seconds{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Seconds between clock ticks"
      },
      {
       "expr": "node_timex_tai_offset_seconds{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "International Atomic Time (TAI) offset"
      }
     ]
    }
   ]
  },
  {
   "title": "System Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context Switches / Interrupts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_context_switches_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "Context switches"
      },
      {
       "expr": "irate(node_intr_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "Interrupts"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "Interrupts Detail",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_interrupts_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ type }} - {{ info }}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Descriptors" }
     ],
     "targets": [
      {
       "expr": "process_max_fds{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Maximum open file descriptors"
      },
      {
       "expr": "process_open_fds{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Open file descriptors"
      }
     ]
    },
    {
     "title": "Entropy",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short", "label": "Entropy" }
     ],
     "targets": [
      {
       "expr": "node_entropy_available_bits{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Entropy available to random number generators"
      }
     ]
    },
    {
     "title": "Processes State",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short", "label": "Processes" }
     ],
     "targets": [
      {
       "expr": "node_procs_blocked{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      },
      {
       "expr": "node_procs_running{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Processes in runnable state"
      }
     ]
    },
    {
     "title": "Processes Forks",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short", "label": "Forks / sec" }
     ],
     "targets": [
      {
       "expr": "irate(node_forks_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "Processes forks second"
      }
     ]
    },
    {
     "title": "Processes Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "decbytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "irate(process_virtual_memory_bytes{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "Processes virtual memory size in bytes"
      },
      {
       "expr": "process_resident_memory_max_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Maximum amount of virtual memory available in bytes"
      },
      {
       "expr": "irate(process_virtual_memory_bytes{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "Processes virtual memory size in bytes"
      }
     ]
    },
    {
     "title": "Hardware temperature monitor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "celsius", "label": "Temperature" }
     ],
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "{{ chip }} {{ sensor }} temp"
      },
      {
       "expr": "node_hwmon_temp_crit_celsius{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "{{ chip }} {{ sensor }} Critical"
      }
     ]
    }
   ]
  },
  {
   "title": "Systemd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Systemd Sockets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_systemd_socket_accepted_connections_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ name }} Connections"
      }
     ]
    },
    {
     "title": "Systemd Units State",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "node_systemd_units{instance=~\"$node:$port\",job=~\"$job\",state=\"activating\"}",
       "legendFormat": "Activating"
      },
      {
       "expr": "node_systemd_units{instance=~\"$node:$port\",job=~\"$job\",state=\"active\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_systemd_units{instance=~\"$node:$port\",job=~\"$job\",state=\"deactivating\"}",
       "legendFormat": "Deactivating"
      },
      {
       "expr": "node_systemd_units{instance=~\"$node:$port\",job=~\"$job\",state=\"failed\"}",
       "legendFormat": "Failed"
      },
      {
       "expr": "node_systemd_units{instance=~\"$node:$port\",job=~\"$job\",state=\"inactive\"}",
       "legendFormat": "Inactive"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IOps Completed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Written bytes"
      }
     ]
    },
    {
     "title": "Disk R/W Time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s", "label": "Time. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Read time"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Write time"
      }
     ]
    },
    {
     "title": "Disk IOs Weighted",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - IO time weighted"
      }
     ]
    },
    {
     "title": "Disk R/W Merged",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "iops", "label": "I/Os" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_merged_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Read merged"
      },
      {
       "expr": "irate(node_disk_writes_merged_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Write merged"
      }
     ]
    },
    {
     "title": "Time Spent Doing I/Os",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - IO time"
      }
     ]
    },
    {
     "title": "Disk IOs Current in Progress",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "iops", "label": "I/Os" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_now{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - IO now"
      }
     ]
    },
    {
     "title": "Open Error File",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "node_textfile_scrape_error{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Textfile scrape error (1 = true)"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem space available",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - Available"
      }
     ]
    },
    {
     "title": "File Nodes Free",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "File Nodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files_free{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - Free file nodes"
      }
     ]
    },
    {
     "title": "File Descriptor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Files" }
     ],
     "targets": [
      {
       "expr": "node_filefd_maximum{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Max open files"
      },
      {
       "expr": "node_filefd_allocated{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Open files"
      }
     ]
    },
    {
     "title": "File Nodes Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "File Nodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - File nodes total"
      }
     ]
    },
    {
     "title": "Filesystem in ReadOnly",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short", "label": "Read Only" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_readonly{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - ReadOnly"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic by Packets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_errs_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive errors"
      },
      {
       "expr": "irate(node_network_transmit_errs_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Rransmit errors"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_drop_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive drop"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Transmit drop"
      }
     ]
    },
    {
     "title": "Network Traffic Compressed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_compressed_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive compressed"
      },
      {
       "expr": "irate(node_network_transmit_compressed_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Transmit compressed"
      }
     ]
    },
    {
     "title": "Network Traffic Multicast",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_multicast_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive multicast"
      }
     ]
    },
    {
     "title": "Network Traffic Fifo",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_fifo_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive fifo"
      },
      {
       "expr": "irate(node_network_transmit_fifo_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Transmit fifo"
      }
     ]
    },
    {
     "title": "Network Traffic Frame",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_frame_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive frame"
      }
     ]
    },
    {
     "title": "Network Traffic Carrier",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_transmit_carrier_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Statistic transmit_carrier"
      }
     ]
    },
    {
     "title": "Network Traffic Colls",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_transmit_colls_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Transmit colls"
      }
     ]
    },
    {
     "title": "NF Contrack",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short", "label": "Entries" }
     ],
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "NF conntrack entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "NF conntrack limit"
      }
     ]
    },
    {
     "title": "ARP Entries",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short", "label": "Entries" }
     ],
     "targets": [
      {
       "expr": "node_arp_entries{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "{{ device }} - ARP entries"
      }
     ]
    },
    {
     "title": "MTU",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_network_mtu_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "{{ device }} - Bytes"
      }
     ]
    },
    {
     "title": "Speed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_network_speed_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "{{ device }} - Speed"
      }
     ]
    },
    {
     "title": "Queue Length",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "none", "label": "Packets" }
     ],
     "targets": [
      {
       "expr": "node_network_transmit_queue_length{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "{{ device }} - Interface transmit queue length"
      }
     ]
    },
    {
     "title": "Network Operational Status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "node_network_up{operstate=\"up\",instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "{{interface}} - Operational state UP"
      },
      {
       "expr": "node_network_carrier{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "{{device}} - Physical link state"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sockstat TCP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "TCP_alloc - Allocated sockets"
      },
      {
       "expr": "node_sockstat_TCP_inuse{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "TCP_inuse - Tcp sockets currently in use"
      },
      {
       "expr": "node_sockstat_TCP_mem{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "TCP_mem - Used memory for tcp"
      },
      {
       "expr": "node_sockstat_TCP_orphan{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "TCP_orphan - Orphan sockets"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "TCP_tw - Sockets wating close"
      }
     ]
    },
    {
     "title": "Sockstat UDP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_UDPLITE_inuse{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "UDPLITE_inuse - Udplite sockets currently in use"
      },
      {
       "expr": "node_sockstat_UDP_inuse{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "UDP_inuse - Udp sockets currently in use"
      },
      {
       "expr": "node_sockstat_UDP_mem{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "UDP_mem - Used memory for udp"
      }
     ]
    },
    {
     "title": "Sockstat Used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_sockets_used{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Sockets_used - Sockets currently in use"
      }
     ]
    },
    {
     "title": "Sockstat Memory Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_mem_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "TCP_mem_bytes - "
      },
      {
       "expr": "node_sockstat_UDP_mem_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "UDP_mem_bytes - "
      }
     ]
    },
    {
     "title": "Sockstat FRAG / RAW",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_FRAG_inuse{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "FRAG_inuse - Frag sockets currently in use"
      },
      {
       "expr": "node_sockstat_FRAG_memory{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "FRAG_memory - Used memory for frag"
      },
      {
       "expr": "node_sockstat_RAW_inuse{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "RAW_inuse - Raw sockets currently in use"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Netstat IP In / Out Octets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "Octects out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_IpExt_InOctets{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "InOctets - Received octets"
      },
      {
       "expr": "irate(node_netstat_IpExt_OutOctets{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "OutOctets - Sent octets"
      }
     ]
    },
    {
     "title": "Netstat IP Forwarding",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "Datagrams" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Ip_Forwarding{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "Forwarding - IP forwarding"
      }
     ]
    },
    {
     "title": "ICMP In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InMsgs{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "InMsgs - Messages which the entity received. Note that this counter includes all those counted by icmpInErrors"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutMsgs{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "OutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors"
      }
     ]
    },
    {
     "title": "ICMP Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InErrors{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "InErrors - Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)"
      }
     ]
    },
    {
     "title": "UDP In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InDatagrams{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "InDatagrams - Datagrams received"
      },
      {
       "expr": "irate(node_netstat_Udp_OutDatagrams{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "OutDatagrams - Datagrams sent"
      }
     ]
    },
    {
     "title": "UDP Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InErrors{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "InErrors - UDP Datagrams that could not be delivered to an application"
      },
      {
       "expr": "irate(node_netstat_Udp_NoPorts{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "NoPorts - UDP Datagrams received on a port with no listener"
      },
      {
       "expr": "irate(node_netstat_UdpLite_InErrors{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "InErrors Lite - UDPLite Datagrams that could not be delivered to an application"
      }
     ]
    },
    {
     "title": "TCP In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_InSegs{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutSegs{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets"
      }
     ]
    },
    {
     "title": "TCP Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
      },
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
      },
      {
       "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
      },
      {
       "expr": "irate(node_netstat_Tcp_InErrs{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
      },
      {
       "expr": "node_netstat_Tcp_MaxConn{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dinamic is \"-1\")"
      }
     ]
    },
    {
     "title": "TCP SynCookie",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "short", "label": "Counter out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "SyncookiesFailed - Invalid SYN cookies received"
      },
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "SyncookiesRecv - SYN cookies received"
      },
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesSent{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "SyncookiesSent - SYN cookies sent"
      }
     ]
    },
    {
     "title": "TCP Direct Transition",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
      },
      {
       "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Exporter Scrape Time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "{{collector}} - Scrape duration"
      }
     ]
    },
    {
     "title": "Node Exporter Scrape Success",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_success{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "{{collector}} - Scrape success"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Cluster Monitoring for Kubernetes",
 "description": "This dashboard provides cluster admins with the ability to monitor nodes and identify workload bottlenecks. It can be deployed with PSPs enabled using the following helm chart - https://github.com/pivotal-cf/charts-grafana",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage ($interval avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{id=\"/\"}) / sum (container_fs_limit_bytes{id=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{id=\"/\"})"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Pods CPU usage ($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Pods network I/O ($interval avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  }
 ]
}
{
 "title": "MySQL Overview",
 "description": "Dashboard from Percona Monitoring and Management project. ",
 "tags": [
  "Percona",
  "MySQL"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up, instance)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MySQL Uptime",
   "type": "singlestat",
   "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "singlestat",
   "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{instance=\"$host\"}[$interval]) or irate(mysql_global_status_queries{instance=\"$host\"}[5m])"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Size",
   "type": "singlestat",
   "description": "**InnoDB Buffer Pool Size**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory. Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_innodb_buffer_pool_size{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Buffer Pool Size of Total RAM",
   "type": "singlestat",
   "description": "**InnoDB Buffer Pool Size % of Total RAM**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory. Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(mysql_global_variables_innodb_buffer_pool_size{instance=\"$host\"} * 100) / on (instance) node_memory_MemTotal_bytes{instance=\"$host\"}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "MySQL Connections",
   "type": "graph",
   "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max(max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval]) or mysql_global_status_threads_connected{instance=\"$host\"} )",
     "legendFormat": "Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_max_used_connections{instance=\"$host\"}",
     "legendFormat": "Max Used Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{instance=\"$host\"}",
     "legendFormat": "Max Connections"
    }
   ]
  },
  {
   "title": "MySQL Client Thread Activity",
   "type": "graph",
   "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[5m])",
     "legendFormat": "Peak Threads Connected"
    },
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_threads_running{instance=\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{instance=\"$host\"}[5m])",
     "legendFormat": "Peak Threads Running"
    },
    {
     "expr": "avg_over_time(mysql_global_status_threads_running{instance=\"$host\"}[$interval]) or \navg_over_time(mysql_global_status_threads_running{instance=\"$host\"}[5m])",
     "legendFormat": "Avg Threads Running"
    }
   ]
  },
  { "title": "Table Locks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "MySQL Questions",
   "type": "graph",
   "description": "**MySQL Questions**\n\nThe number of statements executed by the server. This includes only statements sent to the server by clients and not statements executed within stored programs, unlike the Queries used in the QPS calculation. \n\nThis variable does not count the following commands:\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_questions{instance=\"$host\"}[$interval]) or irate(mysql_global_status_questions{instance=\"$host\"}[5m])",
     "legendFormat": "Questions"
    }
   ]
  },
  {
   "title": "MySQL Thread Cache",
   "type": "graph",
   "description": "**MySQL Thread Cache**\n\nThe thread_cache_size variable sets how many threads the server should cache to reuse. When a client disconnects, the client's threads are put in the cache if the cache is not full. It is autosized in MySQL 5.6.8 and above (capped to 100). Requests for threads are satisfied by reusing threads taken from the cache if possible, and only when the cache is empty is a new thread created.\n\n* *Threads_created*: The number of threads created to handle connections.\n* *Threads_cached*: The number of threads in the thread cache.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_thread_cache_size{instance=\"$host\"}",
     "legendFormat": "Thread Cache Size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_threads_cached{instance=\"$host\"}",
     "legendFormat": "Threads Cached"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_threads_created{instance=\"$host\"}[$interval]) or irate(mysql_global_status_threads_created{instance=\"$host\"}[5m])",
     "legendFormat": "Threads Created"
    }
   ]
  },
  { "title": "Temporary Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "MySQL Temporary Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_created_tmp_tables{instance=\"$host\"}[$interval]) or irate(mysql_global_status_created_tmp_tables{instance=\"$host\"}[5m])",
     "legendFormat": "Created Tmp Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_created_tmp_disk_tables{instance=\"$host\"}[$interval]) or irate(mysql_global_status_created_tmp_disk_tables{instance=\"$host\"}[5m])",
     "legendFormat": "Created Tmp Disk Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_created_tmp_files{instance=\"$host\"}[$interval]) or irate(mysql_global_status_created_tmp_files{instance=\"$host\"}[5m])",
     "legendFormat": "Created Tmp Files"
    }
   ]
  },
  {
   "title": "MySQL Select Types",
   "type": "graph",
   "description": "**MySQL Select Types**\n\nAs with most relational databases, selecting based on indexes is more efficient than scanning an entire table's data. Here we see the counters for selects not done with indexes.\n\n* ***Select Scan*** is how many queries caused full table scans, in which all the data in the table had to be read and either discarded or returned.\n* ***Select Range*** is how many queries used a range scan, which means MySQL scanned all rows in a given range.\n* ***Select Full Join*** is the number of joins that are not joined on an index, this is usually a huge performance hit.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_full_join{instance=\"$host\"}[$interval]) or irate(mysql_global_status_select_full_join{instance=\"$host\"}[5m])",
     "legendFormat": "Select Full Join"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_full_range_join{instance=\"$host\"}[$interval]) or irate(mysql_global_status_select_full_range_join{instance=\"$host\"}[5m])",
     "legendFormat": "Select Full Range Join"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_range{instance=\"$host\"}[$interval]) or irate(mysql_global_status_select_range{instance=\"$host\"}[5m])",
     "legendFormat": "Select Range"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_range_check{instance=\"$host\"}[$interval]) or irate(mysql_global_status_select_range_check{instance=\"$host\"}[5m])",
     "legendFormat": "Select Range Check"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_select_scan{instance=\"$host\"}[$interval]) or irate(mysql_global_status_select_scan{instance=\"$host\"}[5m])",
     "legendFormat": "Select Scan"
    }
   ]
  },
  { "title": "Sorts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "MySQL Sorts",
   "type": "graph",
   "description": "**MySQL Sorts**\n\nDue to a query's structure, order, or other requirements, MySQL sorts the rows before returning them. For example, if a table is ordered 1 to 10 but you want the results reversed, MySQL then has to sort the rows to return 10 to 1.\n\nThis graph also shows when sorts had to scan a whole table or a given range of a table in order to return the results and which could not have been sorted via an index.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_rows{instance=\"$host\"}[$interval]) or irate(mysql_global_status_sort_rows{instance=\"$host\"}[5m])",
     "legendFormat": "Sort Rows"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_range{instance=\"$host\"}[$interval]) or irate(mysql_global_status_sort_range{instance=\"$host\"}[5m])",
     "legendFormat": "Sort Range"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_merge_passes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_sort_merge_passes{instance=\"$host\"}[5m])",
     "legendFormat": "Sort Merge Passes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_sort_scan{instance=\"$host\"}[$interval]) or irate(mysql_global_status_sort_scan{instance=\"$host\"}[5m])",
     "legendFormat": "Sort Scan"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries",
   "type": "graph",
   "description": "**MySQL Slow Queries**\n\nSlow queries are defined as queries being slower than the long_query_time setting. For example, if you have long_query_time set to 3, all queries that take longer than 3 seconds to complete will show on this graph.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_slow_queries{instance=\"$host\"}[$interval]) or irate(mysql_global_status_slow_queries{instance=\"$host\"}[5m])",
     "legendFormat": "Slow Queries"
    }
   ]
  },
  { "title": "Aborted", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "MySQL Aborted Connections",
   "type": "graph",
   "description": "**Aborted Connections**\n\nWhen a given host connects to MySQL and the connection is interrupted in the middle (for example due to bad credentials), MySQL keeps that info in a system table (since 5.6 this table is exposed in performance_schema).\n\nIf the amount of failed requests without a successful connection reaches the value of max_connect_errors, mysqld assumes that something is wrong and blocks the host from further connection.\n\nTo allow connections from that host again, you need to issue the ``FLUSH HOSTS`` statement.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aborted_connects{instance=\"$host\"}[$interval]) or irate(mysql_global_status_aborted_connects{instance=\"$host\"}[5m])",
     "legendFormat": "Aborted Connects (attempts)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aborted_clients{instance=\"$host\"}[$interval]) or irate(mysql_global_status_aborted_clients{instance=\"$host\"}[5m])",
     "legendFormat": "Aborted Clients (timeout)"
    }
   ]
  },
  {
   "title": "MySQL Table Locks",
   "type": "graph",
   "description": "**Table Locks**\n\nMySQL takes a number of different locks for varying reasons. In this graph we see how many Table level locks MySQL has requested from the storage engine. In the case of InnoDB, many times the locks could actually be row locks as it only takes table level locks in a few specific cases.\n\nIt is most useful to compare Locks Immediate and Locks Waited. If Locks waited is rising, it means you have lock contention. Otherwise, Locks Immediate rising and falling is normal activity.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_table_locks_immediate{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_locks_immediate{instance=\"$host\"}[5m])",
     "legendFormat": "Table Locks Immediate"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_table_locks_waited{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_locks_waited{instance=\"$host\"}[5m])",
     "legendFormat": "Table Locks Waited"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "MySQL Network Traffic",
   "type": "graph",
   "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_received{instance=\"$host\"}[$interval]) or irate(mysql_global_status_bytes_received{instance=\"$host\"}[5m])",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_sent{instance=\"$host\"}[$interval]) or irate(mysql_global_status_bytes_sent{instance=\"$host\"}[5m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "MySQL Network Usage Hourly",
   "type": "graph",
   "description": "**MySQL Network Usage Hourly**\n\nHere we can see how much network traffic is generated by MySQL per hour. You can use the bar graph to compare data sent by MySQL and data received by MySQL.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_bytes_received{instance=\"$host\"}[1h])",
     "legendFormat": "Received"
    },
    {
     "calculatedInterval": "2m",
     "expr": "increase(mysql_global_status_bytes_sent{instance=\"$host\"}[1h])",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "MySQL Internal Memory Overview",
   "type": "graph",
   "description": "***System Memory***: Total Memory for the system.\\\n***InnoDB Buffer Pool Data***: InnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.\\\n***TokuDB Cache Size***: Similar in function to the InnoDB Buffer Pool, TokuDB will allocate 50% of the installed RAM for its own cache.\\\n***Key Buffer Size***: Index blocks for MYISAM tables are buffered and are shared by all threads. key_buffer_size is the size of the buffer used for index blocks.\\\n***Adaptive Hash Index Size***: When InnoDB notices that some index values are being accessed very frequently, it builds a hash index for them in memory on top of B-Tree indexes.\\\n ***Query Cache Size***: The query cache stores the text of a SELECT statement together with the corresponding result that was sent to the client. The query cache has huge scalability problems in that only one thread can do an operation in the query cache at the same time.\\\n***InnoDB Dictionary Size***: The data dictionary is InnoDB ‘s internal catalog of tables. InnoDB stores the data dictionary on disk, and loads entries into memory while the server is running.\\\n***InnoDB Log Buffer Size***: The MySQL InnoDB log buffer allows transactions to run without having to write the log to disk before the transactions commit.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$host\"}",
     "legendFormat": "System Memory"
    },
    {
     "expr": "mysql_global_status_innodb_page_size{instance=\"$host\"} * on (instance) mysql_global_status_buffer_pool_pages{instance=\"$host\",state=\"data\"}",
     "legendFormat": "InnoDB Buffer Pool Data"
    },
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size{instance=\"$host\"}",
     "legendFormat": "InnoDB Log Buffer Size"
    },
    {
     "expr": "mysql_global_variables_innodb_additional_mem_pool_size{instance=\"$host\"}",
     "legendFormat": "InnoDB Additional Memory Pool Size"
    },
    {
     "expr": "mysql_global_status_innodb_mem_dictionary{instance=\"$host\"}",
     "legendFormat": "InnoDB Dictionary Size"
    },
    {
     "expr": "mysql_global_variables_key_buffer_size{instance=\"$host\"}",
     "legendFormat": "Key Buffer Size"
    },
    {
     "expr": "mysql_global_variables_query_cache_size{instance=\"$host\"}",
     "legendFormat": "Query Cache Size"
    },
    {
     "expr": "mysql_global_status_innodb_mem_adaptive_hash{instance=\"$host\"}",
     "legendFormat": "Adaptive Hash Index Size"
    },
    {
     "expr": "mysql_global_variables_tokudb_cache_size{instance=\"$host\"}",
     "legendFormat": "TokuDB Cache Size"
    }
   ]
  },
  { "title": "Command, Handlers, Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Top Command Counters",
   "type": "graph",
   "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_global_status_commands_total{instance=\"$host\"}[$interval])>0) or topk(5, irate(mysql_global_status_commands_total{instance=\"$host\"}[5m])>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "Top Command Counters Hourly",
   "type": "graph",
   "description": "**Top Command Counters Hourly**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, increase(mysql_global_status_commands_total{instance=\"$host\"}[1h])>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "MySQL Handlers",
   "type": "graph",
   "description": "**MySQL Handlers**\n\nHandler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and MySQL.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{instance=\"$host\", handler!~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{instance=\"$host\", handler!~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL Transaction Handlers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_handlers_total{instance=\"$host\", handler=~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{instance=\"$host\", handler=~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Process States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_threads{instance=\"$host\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Top Process States Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, avg_over_time(mysql_info_schema_threads{instance=\"$host\"}[1h]))",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "Query Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "MySQL Query Cache Memory",
   "type": "graph",
   "description": "**MySQL Query Cache Memory**\n\nThe query cache has huge scalability problems in that only one thread can do an operation in the query cache at the same time. This serialization is true not only for SELECTs, but also for INSERT/UPDATE/DELETE.\n\nThis also means that the larger the `query_cache_size` is set to, the slower those operations become. In concurrent environments, the MySQL Query Cache quickly becomes a contention point, decreasing performance. MariaDB and AWS Aurora have done work to try and eliminate the query cache contention in their flavors of MySQL, while MySQL 8.0 has eliminated the query cache feature.\n\nThe recommended settings for most environments is to set:\n ``query_cache_type=0``\n ``query_cache_size=0``\n\nNote that while you can dynamically change these values, to completely remove the contention point you have to restart the database.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_qcache_free_memory{instance=\"$host\"}",
     "legendFormat": "Free Memory"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_query_cache_size{instance=\"$host\"}",
     "legendFormat": "Query Cache Size"
    }
   ]
  },
  {
   "title": "MySQL Query Cache Activity",
   "type": "graph",
   "description": "**MySQL Query Cache Activity**\n\nThe query cache has huge scalability problems in that only one thread can do an operation in the query cache at the same time. This serialization is true not only for SELECTs, but also for INSERT/UPDATE/DELETE.\n\nThis also means that the larger the `query_cache_size` is set to, the slower those operations become. In concurrent environments, the MySQL Query Cache quickly becomes a contention point, decreasing performance. MariaDB and AWS Aurora have done work to try and eliminate the query cache contention in their flavors of MySQL, while MySQL 8.0 has eliminated the query cache feature.\n\nThe recommended settings for most environments is to set:\n``query_cache_type=0``\n``query_cache_size=0``\n\nNote that while you can dynamically change these values, to completely remove the contention point you have to restart the database.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_qcache_hits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_qcache_hits{instance=\"$host\"}[5m])",
     "legendFormat": "Hits"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_qcache_inserts{instance=\"$host\"}[$interval]) or irate(mysql_global_status_qcache_inserts{instance=\"$host\"}[5m])",
     "legendFormat": "Inserts"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_qcache_not_cached{instance=\"$host\"}[$interval]) or irate(mysql_global_status_qcache_not_cached{instance=\"$host\"}[5m])",
     "legendFormat": "Not Cached"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_qcache_lowmem_prunes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_qcache_lowmem_prunes{instance=\"$host\"}[5m])",
     "legendFormat": "Prunes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_qcache_queries_in_cache{instance=\"$host\"}",
     "legendFormat": "Queries in Cache"
    }
   ]
  },
  { "title": "Files and Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "MySQL File Openings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_opened_files{instance=\"$host\"}[$interval]) or irate(mysql_global_status_opened_files{instance=\"$host\"}[5m])",
     "legendFormat": "Openings"
    }
   ]
  },
  {
   "title": "MySQL Open Files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_files{instance=\"$host\"}",
     "legendFormat": "Open Files"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_open_files_limit{instance=\"$host\"}",
     "legendFormat": "Open Files Limit"
    },
    {
     "expr": "mysql_global_status_innodb_num_open_files{instance=\"$host\"}",
     "legendFormat": "InnoDB Open Files"
    }
   ]
  },
  { "title": "Table Openings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "MySQL Table Open Cache Status",
   "type": "graph",
   "description": "**MySQL Table Open Cache Status**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_opened_tables{instance=\"$host\"}[$interval]) or irate(mysql_global_status_opened_tables{instance=\"$host\"}[5m])",
     "legendFormat": "Openings"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[5m])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[5m])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_overflows{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_overflows{instance=\"$host\"}[5m])",
     "legendFormat": "Misses due to Overflows"
    },
    {
     "expr": "(rate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[5m]))/((rate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[5m]))+(rate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[5m])))",
     "legendFormat": "Table Open Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "MySQL Open Tables",
   "type": "graph",
   "description": "**MySQL Open Tables**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_tables{instance=\"$host\"}",
     "legendFormat": "Open Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_open_cache{instance=\"$host\"}",
     "legendFormat": "Table Open Cache"
    }
   ]
  },
  { "title": "MySQL Table Definition Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "MySQL Table Definition Cache",
   "type": "graph",
   "description": "**MySQL Table Definition Cache**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_table_definitions{instance=\"$host\"}",
     "legendFormat": "Open Table Definitions"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_definition_cache{instance=\"$host\"}",
     "legendFormat": "Table Definitions Cache Size"
    },
    {
     "expr": "rate(mysql_global_status_opened_table_definitions{instance=\"$host\"}[$interval]) or irate(mysql_global_status_opened_table_definitions{instance=\"$host\"}[5m])",
     "legendFormat": "Opened Table Definitions"
    }
   ]
  },
  { "title": "System Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "I/O Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgin{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=\"$host\"}[5m]) * 1024",
     "legendFormat": "Page In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgout{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=\"$host\"}[5m]) * 1024",
     "legendFormat": "Page Out"
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 137 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal_bytes{instance=\"$host\"} - (node_memory_MemFree_bytes{instance=\"$host\"} + node_memory_Buffers{instance=\"$host\"} + node_memory_Cached{instance=\"$host\"})",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemFree_bytes{instance=\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Buffers{instance=\"$host\"}",
     "legendFormat": "Buffers"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Cached{instance=\"$host\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "CPU Usage / Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 137 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_seconds_total_average{instance=~\"$host\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_seconds_total_average{instance=~\"$host\", mode!=\"total\", mode!=\"idle\"}[5m]))),100)",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "node_load1{instance=\"$host\"}",
     "legendFormat": "Load 1m"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum((rate(node_disk_read_time_seconds_total{device!~\"dm-.+\", instance=\"$host\"}[$interval]) / rate(node_disk_reads_completed_total{device!~\"dm-.+\", instance=\"$host\"}[$interval])) or (irate(node_disk_read_time_seconds_total{device!~\"dm-.+\", instance=\"$host\"}[5m]) / irate(node_disk_reads_completed_total{device!~\"dm-.+\", instance=\"$host\"}[5m]))\nor avg_over_time(aws_rds_read_latency_average{instance=\"$host\"}[$interval]) or avg_over_time(aws_rds_read_latency_average{instance=\"$host\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum((rate(node_disk_write_time_seconds_total{device!~\"dm-.+\", instance=\"$host\"}[$interval]) / rate(node_disk_writes_completed_total{device!~\"dm-.+\", instance=\"$host\"}[$interval])) or (irate(node_disk_write_time_seconds_total{device!~\"dm-.+\", instance=\"$host\"}[5m]) / irate(node_disk_writes_completed_total{device!~\"dm-.+\", instance=\"$host\"}[5m])) or \navg_over_time(aws_rds_write_latency_average{instance=\"$host\"}[$interval]) or avg_over_time(aws_rds_write_latency_average{instance=\"$host\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 144 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$host\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes_total{instance=\"$host\", device!=\"lo\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{instance=\"$host\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{instance=\"$host\"}[5m])) ",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$host\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes_total{instance=\"$host\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{instance=\"$host\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{instance=\"$host\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 144 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpin{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap In (Reads)"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpout{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap Out (Writes)"
    }
   ]
  }
 ]
}
{
 "title": "Consul Exporter Dashboard",
 "description": "Consul Exporter Dashboar for Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Services",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_catalog_services", "legendFormat": "{{app}}" }
   ]
  },
  {
   "title": "Consul Peers and Leaders",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_raft_peers", "legendFormat": "peers" },
    { "expr": "consul_raft_leader", "legendFormat": "leader" },
    { "expr": "consul_serf_lan_members", "legendFormat": "serf_lan_members" }
   ]
  },
  {
   "title": "Unhealthy Consul Services",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name, status) (consul_health_service_status{status!=\"passing\"})",
     "legendFormat": "{{service_name}} - {{status}}"
    }
   ]
  },
  {
   "title": "Unhealthy Consul Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consul_health_node_status{status!='passing'}",
     "legendFormat": "{{node}} - {{status}}"
    }
   ]
  },
  {
   "title": "Consul Services and Checks",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node,service_id,status) (consul_health_service_status)",
     "legendFormat": "{{node}} - {{service_id}} - {{status}}"
    }
   ]
  }
 ]
}