---
- hosts: ELK_server
  become: yes
  become_method: sudo
  tasks:
    - include_role:
        name: docker
    - include_role:
        name: ELK
      when: inventory_hostname in groups['ELK_server']
        
    - name: Flush all handlers.
      meta: flush_handlers

